version: "3.3"

services:
  timebot:
    # image: ghcr.io/josiahbull/timebot:main
    build: .
    container_name: timebot
    restart: always
    environment:
      - DISCORD_TOKEN
      - TZ

  autoheal:
    restart: unless-stopped
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - timebot
